Update Jenkinsfile

diff --git a/spring-boot-app/Jenkinsfile b/spring-boot-app/Jenkinsfile
--- a/spring-boot-app/Jenkinsfile
+++ b/spring-boot-app/Jenkinsfile
@@ -57,11 +57,17 @@ pipeline {
             steps {
                 dir('spring-boot-app-manifests') {
                     sh '''
-                        sed -i "s@image:.*@image: $IMAGE_NAME@g" deployment.yaml
+                        if [ -f deployment.yaml ]; then
+                            sed -i "s@image:.*@image: $IMAGE_NAME@g" deployment.yaml
+                        else
+                            echo "deployment.yaml not found!"
+                        exit 1
+                        fi
                     '''
                 }
             }
         }
+
 
         stage('Commit and Push Changes') {
             steps {
